#!/usr/bin/env python3
"""Regenerate ``src/untether_bt/_assigned_numbers.py`` from the authoritative registries.

Run this when the Bluetooth SIG publishes new Assigned Numbers:

    python tools/gen_assigned_numbers.py

Sources (facts, not specification text — redistributed with attribution):
  * Bluetooth SIG Assigned Numbers — https://bitbucket.org/bluetooth-SIG/public
    (service classes, protocol identifiers, AD types, appearance, class of device)
  * NordicSemiconductor/bluetooth-numbers-database (mirrors the SIG GSS registry)
    for company IDs + GATT service/characteristic/descriptor UUIDs.

The generated module is pure Python literals, so the shipped library needs no network
access and no YAML/JSON parser at runtime. Requires ``pyyaml`` to run the generator.
"""

from __future__ import annotations

import json
import urllib.request

import yaml

NORDIC = "https://raw.githubusercontent.com/NordicSemiconductor/bluetooth-numbers-database/master/v1"
SIG = "https://bitbucket.org/bluetooth-SIG/public/raw/HEAD/assigned_numbers"

OUT = __file__.rsplit("/", 2)[0] + "/src/untether_bt/_assigned_numbers.py"


def _get(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=30) as r:  # noqa: S310 - fixed https sources
        return r.read()


def _json(url: str):
    return json.loads(_get(url))


def _yaml(url: str):
    return yaml.safe_load(_get(url))


def _hex(u: str) -> int:
    return int(u, 16)


def _u16_map(rows: list, uuid_key: str = "uuid", name_key: str = "name") -> dict[int, str]:
    """Keep only 16-bit (base-UUID) entries; skip vendor 128-bit UUIDs."""
    out: dict[int, str] = {}
    for x in rows:
        u = x[uuid_key]
        if isinstance(u, int):          # YAML parsed 0x.... as an int already
            val = u
        elif len(u.lower().removeprefix("0x")) <= 4:  # 16-bit, not a 128-bit vendor UUID
            val = _hex(u)
        else:
            continue
        if val <= 0xFFFF:
            out[val] = x[name_key]
    return out


def _lit(s: str) -> str:
    """A safely-escaped Python string literal (json.dumps emits valid double-quoted literals)."""
    return json.dumps(" ".join(str(s).split()))  # also collapses stray whitespace/newlines


def _fmt_int_dict(d: dict[int, str], width: int) -> str:
    return "\n".join(f"    0x{k:0{width}X}: {_lit(d[k])}," for k in sorted(d))


def main() -> None:
    companies = {x["code"]: x["name"] for x in _json(f"{NORDIC}/company_ids.json")}
    services = _u16_map(_json(f"{NORDIC}/service_uuids.json"))
    chars = _u16_map(_json(f"{NORDIC}/characteristic_uuids.json"))
    descs = _u16_map(_json(f"{NORDIC}/descriptor_uuids.json"))

    svc_classes = _u16_map(_yaml(f"{SIG}/uuids/service_class.yaml")["uuids"])
    protocols = _u16_map(_yaml(f"{SIG}/uuids/protocol_identifiers.yaml")["uuids"])
    ad_types = {x["value"]: x["name"] for x in _yaml(f"{SIG}/core/ad_types.yaml")["ad_types"]}

    appearance = _yaml(f"{SIG}/core/appearance_values.yaml")["appearance_values"]
    appear_cat = {x["category"]: x["name"] for x in appearance}
    appear_sub = {
        x["category"]: {s["value"]: s["name"] for s in x.get("subcategory", [])}
        for x in appearance
        if x.get("subcategory")
    }

    cod = _yaml(f"{SIG}/core/class_of_device.yaml")
    cod_service = {x["bit"]: x["name"] for x in cod["cod_services"]}
    cod_major = {x["major"]: x["name"] for x in cod["cod_device_class"]}
    cod_minor = {
        x["major"]: {m["value"]: m["name"] for m in x.get("minor", [])}
        for x in cod["cod_device_class"]
        if x.get("minor")
    }

    def fmt_nested(d: dict[int, dict[int, str]]) -> str:
        out = []
        for k in sorted(d):
            inner = ", ".join(f"0x{i:02X}: {_lit(d[k][i])}" for i in sorted(d[k]))
            out.append(f"    0x{k:X}: {{{inner}}},")
        return "\n".join(out)

    counts = {
        "company IDs": len(companies), "GATT services": len(services),
        "GATT characteristics": len(chars), "GATT descriptors": len(descs),
        "SDP service classes": len(svc_classes), "protocol identifiers": len(protocols),
        "AD types": len(ad_types), "appearance categories": len(appear_cat),
    }
    header = (
        '"""AUTO-GENERATED by tools/gen_assigned_numbers.py — do not edit by hand.\n\n'
        "Bluetooth Assigned Numbers, sourced from the Bluetooth SIG\n"
        "(bitbucket.org/bluetooth-SIG/public) and the NordicSemiconductor\n"
        "bluetooth-numbers-database mirror. These are factual registry entries.\n\n"
        "Counts: " + ", ".join(f"{v} {k}" for k, v in counts.items()) + ".\n"
        '"""\n\nfrom __future__ import annotations\n\n'
    )

    body = (
        f"COMPANY_IDS: dict[int, str] = {{\n{_fmt_int_dict(companies, 4)}\n}}\n\n"
        f"GATT_SERVICES: dict[int, str] = {{\n{_fmt_int_dict(services, 4)}\n}}\n\n"
        f"GATT_CHARACTERISTICS: dict[int, str] = {{\n{_fmt_int_dict(chars, 4)}\n}}\n\n"
        f"GATT_DESCRIPTORS: dict[int, str] = {{\n{_fmt_int_dict(descs, 4)}\n}}\n\n"
        f"SDP_SERVICE_CLASSES: dict[int, str] = {{\n{_fmt_int_dict(svc_classes, 4)}\n}}\n\n"
        f"PROTOCOL_IDS: dict[int, str] = {{\n{_fmt_int_dict(protocols, 4)}\n}}\n\n"
        f"AD_TYPES: dict[int, str] = {{\n{_fmt_int_dict(ad_types, 2)}\n}}\n\n"
        f"APPEARANCE_CATEGORIES: dict[int, str] = {{\n{_fmt_int_dict(appear_cat, 3)}\n}}\n\n"
        f"APPEARANCE_SUBCATEGORIES: dict[int, dict[int, str]] = {{\n{fmt_nested(appear_sub)}\n}}\n\n"
        f"COD_MAJOR_SERVICE_CLASSES: dict[int, str] = {{\n{_fmt_int_dict(cod_service, 2)}\n}}\n\n"
        f"COD_MAJOR_DEVICE_CLASSES: dict[int, str] = {{\n{_fmt_int_dict(cod_major, 2)}\n}}\n\n"
        f"COD_MINOR_DEVICE_CLASSES: dict[int, dict[int, str]] = {{\n{fmt_nested(cod_minor)}\n}}\n"
    )

    with open(OUT, "w") as f:
        f.write(header + body)
    print(f"wrote {OUT}")
    for k, v in counts.items():
        print(f"  {v:>5} {k}")


if __name__ == "__main__":
    main()
